### PR TITLE
No Categories

### PR DESCRIPTION
**Pull request by AtticusKuhn**
Upon the advice of Conal Elliott, I am going to formalize binary arithmetic without using categories.

### CODE REVIEW

**Comment by AtticusKuhn** [comment]
I added a function extensionality axiom

```agda
  pfunext : {x y a b : Set} {f : x → y} {g : a → b} → ⦃ tyb : hasT y b ⦄ → ⦃ txa : hasT x a ⦄  →  ( (h : x) → (p⟦ f h ⟧) ≡ g (p⟦ h ⟧)) → p⟦ f ⟧ ≡ g
```
Basically, if  ∀ x → ⟦ f x ⟧ ≡ g ⟦ x ⟧ , then  ⟦ f ⟧ ≡ g. Hopefully this axiom is sound.

**Comment by conal** [comment]
> Hopefully this axiom is sound.

What do you mean by "sound" for an axiom?

**Comment by AtticusKuhn** [comment]
> What do you mean by "sound" for an axiom?

Perhaps a better word than "sound" is "correct".

**Comment by conal** [comment]
> > What do you mean by "sound" for an axiom?
> 
> Perhaps a better word than "sound" is "correct".

Okay. What do you mean by "correct" for an axiom?

**Pull request merged**
